version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=rootuser
      - MONGO_INIT_DB_ROOT_PASSWORD=19A12iou#
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMIN_USERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMIN_PASSWORD=19A12iou#
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network